name: Build and Publish Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t  malsuelibi/nginx-static-website:latest .
          docker tag malsuelibi/nginx-static-website:latest malsuelibi/nginx-static-website:${{ github.sha }}

      - name: Push Docker images to Docker Hub
        run: |
          docker push malsuelibi/nginx-static-website:latest
          docker push malsuelibi/nginx-static-website:${{ github.sha }}

