version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    networks:
      - mynetwork

networks:
  mynetwork:
