version: '3'
services:
  nginx-static-website:
    build:
      context: .
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always